name: build

on:
  push:
    branches:
    - master

jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Install packages
      run: |
        sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        sudo sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        sudo echo -e '[extremscorner-devkitpro]\nServer = https://packages.extremscorner.org/devkitpro/linux/$arch' >> /opt/devkitpro/pacman/etc/pacman.conf
        sudo dkp-pacman -Sy
        sudo dkp-pacman -S --noconfirm --ask 4 gamecube-tools-git libogc2 libogc2-libdvm libogc2-opengx libogc2-glu libogc2-sdl2 ppc-glm ppc-libpng libogc2-cmake ppc-zlib-ng-compat

    - name: add ppc gcc to PATH environment variable
      uses: myci-actions/export-env-var@1
      with:
        name: PATH
        value: $PATH:/opt/devkitpro/devkitPPC/bin

    - name: Export CFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Export CXXFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CXXFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_EXAMPLES=ON -DBUILD_OPENGX=OFF

    - name: Build
      run: cmake --build build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-build-artifacts
        path: .
